name: Atualizar Resultados das Loterias

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *' # Roda todo dia às 8h UTC (5h no Brasil)

jobs:
  update_loterias:
    runs-on: ubuntu-latest
    strategy:
      matrix: # TODO: Adicionar outras loterias ao matrix se necessário
        lottery: [quina] # [quina, megasena, lotofacil] # Lista de loterias a serem atualizadas
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Usar Python 3.11 para consistência

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar script de atualização para ${{ matrix.lottery }}
        run: python scripts/update.py ${{ matrix.lottery }}

      - name: Commit e Push das alterações para ${{ matrix.lottery }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Atualiza resultados da ${{ matrix.lottery }}'
          file_pattern: 'data/${{ matrix.lottery }}.csv'
          # Adicionar um token com permissão de escrita, se necessário, para o auto-commit
          # token: ${{ secrets.GITHUB_TOKEN }}
